### ISSUE TITLE
Black Screen on Cardputer, installed from M5Burner

### ISSUE THREAD

**Issue by raxp122** [dj1ch/minigotchi-ESP32#100]
The screen is black

**To Reproduce**
Flash Minigotchi-ESP32 Cardputer from M5Burner

**Expected behavior**
The screen should show something

**Comment by dj1ch** [comment]
> The screen is black
> 
> **To Reproduce** Flash Minigotchi-ESP32 Cardputer from M5Burner
> 
> **Expected behavior** The screen should show something

Are you able to manually build the firmware? At the moment I don't have a cardputer but I'll try to rebuild the image for the M5Burner. 

Just to check, can you make sure there's serial output on the Minigotchi?

**Comment by raxp122** [comment]
No sorry i don't really know how to build the firmware myself. I connected the cardputer to arduino Ide, connected to the Com port and this is the output:

nvalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xfESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x7 (TG0WDT_SYS_RST),boot:0x2b (SPI_FAST_FLASH_BOOT)
Saved PC:0x40048839
invalid header: 0xffffffff
invalid header: 0xffffffff

**Comment by dj1ch** [comment]
> No sorry i don't really know how to build the firmware myself. I connected the cardputer to arduino Ide, connected to the Com port and this is the output:
> 
> nvalid header: 0xffffffff invalid header: 0xffffffff invalid header: 0xfESP-ROM:esp32s3-20210327 Build:Mar 27 2021 rst:0x7 (TG0WDT_SYS_RST),boot:0x2b (SPI_FAST_FLASH_BOOT) Saved PC:0x40048839 invalid header: 0xffffffff invalid header: 0xffffffff

This means that whatever you flashed, it isn't compatible with your Cardputer's WiFi card (usually it's the ESP32S3). The install guide is [here](https://github.com/dj1ch/minigotchi-ESP32/blob/main/INSTALL.md) in case you need it.

> Edit: is this supposed to work also by launching it from M5Launcher or it will only work if flashed directly?

No, it's not meant to be ran through M5Launcher. It can either be manually installed via the [install guide](https://github.com/dj1ch/minigotchi-ESP32/blob/main/INSTALL.md) (I compiled with the `ESP32S3 Dev Module` option) or flashed through M5Burner. If you just compile straight away with Arduino IDE you'll run into issues.

**Comment by raxp122** [comment]
Ok so the issue is with the compiled version in M5Burner? let me know if you recompile it so i will try again flashing from there
