### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ATOMNFT** [dj1ch/minigotchi-ESP32#35]
C:\Users\itsme\Desktop\minigotchi-ESP32\pwnagotchi.cpp: In static member function 'static void Pwnagotchi::detect()':
C:\Users\itsme\Desktop\minigotchi-ESP32\pwnagotchi.cpp:95:50: error: 'name' was not declared in this scope
     Parasite::sendPwnagotchiStatus(FRIEND_FOUND, name.c_str());
                                                  ^~~~
C:\Users\itsme\Desktop\minigotchi-ESP32\pwnagotchi.cpp:95:50: note: suggested alternative: 'Frame'
     Parasite::sendPwnagotchiStatus(FRIEND_FOUND, name.c_str());
                                                  ^~~~
                                                  Frame

exit status 1

Compilation error: 'name' was not declared in this scope

I added std::string name; to the void Pwnagotchi::detect() and it compiles and flashes.

**Comment by dj1ch** [comment]
should be fixed in the development branch, ill close this issue now
