### ISSUE TITLE
missing file or directory issue

### ISSUE THREAD

**Issue by skratch420** [dj1ch/minigotchi-ESP32#71]
i followed the install guide step by step word for word for the ESP32 install 
and i keep getting this error. im not super familiar with the arduino IDE or arduino file structures. any help would be appreciated 

<img width="531" alt="Screenshot 2024-08-16 212558" src="https://github.com/user-attachments/assets/2685ade8-3e5b-4257-a078-f04bad07217c">

**Comment by dj1ch** [comment]
Looks like the issue here is your platform.txt. I made an example one [here](https://github.com/dj1ch/minigotchi-ESP32/blob/main/misc/platform.txt) if you want to double check that your configuration is valid.
