### ISSUE TITLE
display issues

### ISSUE THREAD

**Issue by skratch420** [dj1ch/minigotchi-ESP32#83]
so iam using a CYD and i have finally successfully uploaded myb sketch but for some reason the display is not working at all.

in the arduino IDE in the serial monitor it appears that everything is working
( its scanning APs and showing packets per second and what channel its scanning)
but for some reason the display on the CYD is doing absolutely nothing.

again i followed the vinstall instructions to a T but am unable to figure this out.
i have set in the display.ccp settings to CYD

**Comment by dj1ch** [comment]
can you send me your config.cpp just to make sure everything for the configuration is correct?
